### PR TITLE
Fix inline documentation for hooks to follow WordPress Coding Standards

### LINKED ISSUE #815: Inline documentation for hooks (filters & actions) does not follow WordPress Coding Standards
Our codebase currently contains multiple filters and actions whose inline documentation does not meet the official WordPress Inline Documentation Standards for PHP, particularly the section on documenting hooks.

According to the WordPress Coding Standards, all hooks must have complete, structured DocBlocks, including summary, description, `@since`, `@param`, and `@return` tags. The standard explicitly states that hooks (actions and filters) must be documented just like functions, with clear descriptions of what is being filtered and what parameters are passed.

https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters

### PR DESCRIPTION
**Pull request by aslamdoctor**
## Summary
- Fixes #815
- Adds missing DocBlocks for undocumented hooks (`two_factor_rest_api_can_edit_user`, `two_factor_user_authenticated`, `two_factor_user_revalidated`, `two_factor_rememberme`, `two_factor_before_authentication_prompt`, `two_factor_after_authentication_prompt`, `two_factor_after_authentication_input`, `two_factor_totp_time_step_allowance`)
- Adds missing `@since` tags to all hook DocBlocks across the codebase
- Replaces non-standard `@var` with proper `@param` in `two_factor_backup_code_length`
- Adds cross-reference comments (`/** This action is documented in ... */`) for repeated hooks across providers

## Details
This PR brings all hook (filter & action) inline documentation in line with the [WordPress Inline Documentation Standards for PHP](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters). Changes are documentation-only — no functional code was modified.

## Test plan
- [ ] Verify no functional changes — all edits are inside `/** ... */` comment blocks
- [ ] Confirm DocBlocks follow WordPress Coding Standards (summary, `@since`, `@param` tags)
- [ ] Run existing test suite to confirm nothing is broken

### CODE REVIEW

File: providers/class-two-factor-backup-codes.php [hunk 1]
```diff
@@ -386,14 +388,41 @@ public function authentication_page( $user ) {
...
 		<p>
 			<label for="authcode"><?php esc_html_e( 'Recovery Code:', 'two-factor' ); ?></label>
 			<input type="text" inputmode="numeric" name="two-factor-backup-code" id="authcode" class="input authcode" value="" size="20" pattern="[0-9 ]*" placeholder="<?php echo esc_attr( $code_placeholder ); ?>" data-digits="<?php echo esc_attr( $code_length ); ?>" />
 		</p>
-		<?php do_action( 'two_factor_after_authentication_input', $this ); ?>
+		<?php
+		/**
+		 * Fires after the two-factor authentication input field.
+		 *
+		 * @since 0.1-dev
```
Comment (masteradhoc) [inline providers/class-two-factor-backup-codes.php]:
```suggestion
		 * @since 0.15.0
```

this was added in #742

File: providers/class-two-factor-email.php [hunk 2]
```diff
@@ -169,22 +171,23 @@ public function user_token_ttl( $user_id ) {
...
-		 * after the generation.
+		 * Filters the number of seconds the email token is considered valid after generation.
 		 *
+		 * @since 0.1-dev
 		 * @deprecated 0.11.0 Use {@see 'two_factor_email_token_ttl'} instead.
 		 *
-		 * @param integer $token_ttl Token time-to-live in seconds.
-		 * @param integer $user_id User ID.
+		 * @param int $token_ttl Token time-to-live in seconds.
+		 * @param int $user_id   User ID.
```
Comment (masteradhoc) [inline providers/class-two-factor-email.php]:
```suggestion
		 * @param int $user_id User ID.
```

nitpick but not as many spaces needed.

File: providers/class-two-factor-totp.php [hunk 3]
```diff
@@ -641,13 +650,25 @@ public static function get_authcode_valid_ticktime( $key, $authcode, $hash = sel
 		 * Filter the maximum ticks to allow when checking valid codes.
 		 *
 		 * Ticks are the allowed offset from the correct time in 30 second increments,
-		 * so the default of 4 allows codes that are two minutes to either side of server time
+		 * so the default of 4 allows codes that are two minutes to either side of server time.
 		 *
+		 * @since 0.1-dev
```
Comment (masteradhoc) [inline providers/class-two-factor-totp.php]:
```suggestion
		 * @since 0.2.0
```

see #31

File: class-two-factor-core.php [hunk 4]
```diff
@@ -1569,6 +1595,14 @@ public static function _login_form_validate_2fa( $user, $nonce = '', $provider =
 
 		wp_set_auth_cookie( $user->ID, $rememberme );
 
+		/**
+		 * Fires after a user has been authenticated via two-factor.
+		 *
+		 * @since 0.1-dev
```
Comment (masteradhoc) [inline class-two-factor-core.php]:
```suggestion
		 * @since 0.5.2
```

was added in (https://github.com/WordPress/two-factor/pull/324)

**Review by masteradhoc — CHANGES_REQUESTED** [review]
Hey @aslamdoctor 
Went through the PR and gave you several commitable feedbacks to check. Please see and let me know.

File: providers/class-two-factor-backup-codes.php [hunk 5]
```diff
@@ -386,14 +388,41 @@ public function authentication_page( $user ) {
 		$code_placeholder = str_repeat( 'X', $code_length );
 
 		?>
-		<?php do_action( 'two_factor_before_authentication_prompt', $this ); ?>
+		<?php
+		/**
+		 * Fires before the two-factor authentication prompt text.
+		 *
+		 * @since 0.1-dev
```
[the remark this answers is not in the document]
Comment (aslamdoctor) [reply providers/class-two-factor-backup-codes.php]: Addressed in a623f28.

File: providers/class-two-factor-email.php (hunk 2 above)
Comment (aslamdoctor) [reply providers/class-two-factor-email.php]: Addressed in a623f28.

File: providers/class-two-factor-email.php [hunk 6]
```diff
@@ -169,22 +171,23 @@ public function user_token_ttl( $user_id ) {
 		$token_ttl = 15 * MINUTE_IN_SECONDS;
 
 		/**
-		 * Number of seconds the token is considered valid
-		 * after the generation.
+		 * Filters the number of seconds the email token is considered valid after generation.
 		 *
+		 * @since 0.1-dev
```
[the remark this answers is not in the document]
Comment (aslamdoctor) [reply providers/class-two-factor-email.php]: Addressed in a623f28.

File: providers/class-two-factor-totp.php (hunk 3 above)
Comment (aslamdoctor) [reply providers/class-two-factor-totp.php]: Addressed in a623f28.

**Review by masteradhoc — APPROVED** [review]
